# Required Python packages:
#
# ansible
# openstackclient
# openstacksdk

- import_playbook: common.yaml

- hosts: all
  gather_facts: no

  tasks:
  - name: 'List ports attatched to router'
    command:
      cmd: "openstack port list --device-owner=network:router_interface --tags {{ cluster_id_tag }} -f value -c id"
    register: router_ports

  - name: 'Remove the ports from router'
    command:
      cmd: "openstack router remove port {{ os_router }} {{ item.1}}"
    with_indexed_items: "{{ router_ports.stdout_lines }}"

  - name: 'List ha ports attached to router'
    command:
      cmd: "openstack port list --device-owner=network:ha_router_replicated_interface --tags {{ cluster_id_tag }} -f value -c id"
    register: ha_router_ports

  - name: 'Remove the ha ports from router'
    command:
      cmd: "openstack router remove port {{ os_router }} {{ item.1}}"
    with_indexed_items: "{{ ha_router_ports.stdout_lines }}"

  - name: 'List ports'
    command:
      cmd: "openstack port list --tags {{ cluster_id_tag }} -f value -c id "
    register: ports

  - name: 'Remove the cluster ports'
    command:
      cmd: "openstack port delete {{ item.1}}"
    with_indexed_items: "{{ ports.stdout_lines }}"

  - name: 'Remove the cluster router'
    os_router:
      name: "{{ os_router }}"
      state: absent

  - name: 'List cluster networks'
    command:
      cmd: "openstack network list --tags {{ cluster_id_tag }} -f value -c Name"
    register: networks

  - name: 'Remove the cluster networks'
    os_network:
      name: "{{ item.1}}"
      state: absent
    with_indexed_items: "{{ networks.stdout_lines }}"

  - name: 'List the cluster subnet pool'
    command:
      cmd: "openstack subnet pool list --name {{ subnet_pool }}"
    when: os_networking_type == "Kuryr"
    register: pods_subnet_pool

  - name: 'Remove the cluster subnet pool'
    command:
      cmd: "openstack subnet pool delete {{ subnet_pool }}"
    when:
    - os_networking_type == "Kuryr"
    - pods_subnet_pool.stdout != ""
